import { RESPONSE_TYPE, type ResponseType } from './response-type';

export const RESPONSE_CODE = {
    // --- auth success ---
    MAGIC_LINK_SENT: 'MAGIC_LINK_SENT',
    LOGGED_OUT: 'LOGGED_OUT',
    PASSWORD_SET: 'PASSWORD_SET',
    PASSWORD_RESET: 'PASSWORD_RESET',
    ACCOUNT_DELETED: 'ACCOUNT_DELETED',
    ACCOUNT_RESTORED: 'ACCOUNT_RESTORED',

    // --- users success ---
    TERMS_ACCEPTED: 'TERMS_ACCEPTED',
    EXECUTIONS_SPENT: 'EXECUTIONS_SPENT',

    // --- payments error ---
    ALREADY_SUBSCRIBED: 'ALREADY_SUBSCRIBED',
    SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
    NO_BILLING_ACCOUNT: 'NO_BILLING_ACCOUNT',
    PAYMENT_TYPE_DISABLED: 'PAYMENT_TYPE_DISABLED',

    // --- onboarding error ---
    ONBOARDING_INCOMPLETE: 'ONBOARDING_INCOMPLETE',

    // --- ai error ---
    AI_RATE_LIMIT_EXCEEDED: 'AI_RATE_LIMIT_EXCEEDED',
    AI_MESSAGE_TOO_LONG: 'AI_MESSAGE_TOO_LONG',

    // --- executions error ---
    EXECUTIONS_RESERVATION_ACTIVE: 'EXECUTIONS_RESERVATION_ACTIVE',

    // --- storage success ---
    AVATAR_UPDATED: 'AVATAR_UPDATED',
    AVATAR_DELETED: 'AVATAR_DELETED',

    // --- storage error ---
    AVATAR_UPLOAD_FAILED: 'AVATAR_UPLOAD_FAILED',
    AVATAR_FILE_KEY_INVALID: 'AVATAR_FILE_KEY_INVALID',
    AVATAR_UPLOAD_NOT_FOUND: 'AVATAR_UPLOAD_NOT_FOUND',
    AVATAR_UPLOAD_INVALID: 'AVATAR_UPLOAD_INVALID',

    // --- errors ---
    UNAUTHORIZED: 'UNAUTHORIZED',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    INSUFFICIENT_EXECUTIONS: 'INSUFFICIENT_EXECUTIONS',
    EMAIL_SEND_FAILED: 'EMAIL_SEND_FAILED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ResponseCode =
    (typeof RESPONSE_CODE)[keyof typeof RESPONSE_CODE];

/** Маппінг код → тип для фронту (колір нотифікації тощо) */
export const RESPONSE_CODE_TYPE: Record<ResponseCode, ResponseType> = {
    [RESPONSE_CODE.MAGIC_LINK_SENT]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.LOGGED_OUT]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.PASSWORD_SET]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.PASSWORD_RESET]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.TERMS_ACCEPTED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.ACCOUNT_DELETED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.ACCOUNT_RESTORED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.EXECUTIONS_SPENT]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.ALREADY_SUBSCRIBED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.SUBSCRIPTION_REQUIRED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.NO_BILLING_ACCOUNT]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.PAYMENT_TYPE_DISABLED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.AI_RATE_LIMIT_EXCEEDED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.AI_MESSAGE_TOO_LONG]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.EXECUTIONS_RESERVATION_ACTIVE]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.AVATAR_UPDATED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.AVATAR_DELETED]: RESPONSE_TYPE.SUCCESS,
    [RESPONSE_CODE.AVATAR_UPLOAD_FAILED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.AVATAR_FILE_KEY_INVALID]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.AVATAR_UPLOAD_NOT_FOUND]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.AVATAR_UPLOAD_INVALID]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.ONBOARDING_INCOMPLETE]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.UNAUTHORIZED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.VALIDATION_ERROR]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.NOT_FOUND]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.RATE_LIMIT_EXCEEDED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.INSUFFICIENT_EXECUTIONS]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.EMAIL_SEND_FAILED]: RESPONSE_TYPE.ERROR,
    [RESPONSE_CODE.INTERNAL_ERROR]: RESPONSE_TYPE.ERROR,
};
